using System.Reflection;
using IdeaBoard.Shared.DataEntities;
using IdeaBoard.Shared.Services;

namespace IdeaBoard.Shared.DataServices;

public abstract class BaseDataService<TEntity> where TEntity : class
{
    protected readonly SupabaseService SupabaseService;
    protected readonly string TableName;

    protected BaseDataService(SupabaseService supabaseService)
    {
        SupabaseService = supabaseService;
        TableName = GetTableName();
    }

    /// <summary>
    /// Gets the table name from the [Table] attribute on the entity.
    /// </summary>
    private string GetTableName()
    {
        var tableAttribute = typeof(TEntity).GetCustomAttribute<TableAttribute>();
        if (tableAttribute == null)
        {
            throw new InvalidOperationException(
                $"Entity {typeof(TEntity).Name} must have a [Table] attribute.");
        }
        return tableAttribute.Name;
    }

    /// <summary>
    /// Gets all records for the current user (RLS enforced by auth token).
    /// </summary>
    public virtual async Task<List<TEntity>> GetAllAsync()
    {
        return await SupabaseService.GetAsync<TEntity>(TableName);
    }

    /// <summary>
    /// Gets a single record by ID (RLS enforced by auth token).
    /// </summary>
    public virtual async Task<TEntity?> GetByIdAsync(Guid id)
    {
        return await SupabaseService.GetByIdAsync<TEntity>(TableName, id);
    }

    /// <summary>
    /// Creates a new record. ID and timestamps are auto-generated by the database.
    /// </summary>
    public virtual async Task<TEntity> CreateAsync(TEntity entity)
    {
        // Note: ID, CreatedAt, and UpdatedAt are auto-generated by database defaults
        // Do not set these values in the application code
        return await SupabaseService.PostAsync(TableName, entity);
    }

    /// <summary>
    /// Updates an existing record. UpdatedAt timestamp is auto-updated by database trigger.
    /// </summary>
    public virtual async Task<TEntity> UpdateAsync(Guid id, TEntity entity)
    {
        // Note: UpdatedAt is auto-updated by database trigger
        // Do not set this value in the application code
        return await SupabaseService.UpdateByIdAsync(TableName, id, entity);
    }

    /// <summary>
    /// Deletes a record (RLS enforced by auth token).
    /// </summary>
    public virtual async Task<bool> DeleteAsync(Guid id)
    {
        return await SupabaseService.DeleteByIdAsync(TableName, id);
    }
}
