using IdeaBoard.Features.Boards.Models;
using IdeaBoard.Shared.Services;
using Microsoft.AspNetCore.Components.Authorization;
using System.Security.Claims;

namespace IdeaBoard.Features.Boards.Services;

public class BoardService
{
    private readonly SupabaseService _supabaseService;
    private readonly AuthenticationStateProvider _authStateProvider;

    public BoardService(
        SupabaseService supabaseService,
        AuthenticationStateProvider authStateProvider)
    {
        _supabaseService = supabaseService;
        _authStateProvider = authStateProvider;
    }

    /// <summary>
    /// Gets all boards for the current user, ordered by last updated (newest first).
    /// </summary>
    public async Task<List<Board>> GetBoardsAsync()
    {
        var userId = await GetCurrentUserIdAsync();
        if (userId == Guid.Empty)
        {
            throw new UnauthorizedAccessException("User is not authenticated.");
        }

        // Query Supabase: GET /rest/v1/boards?user_id=eq.{userId}&order=updated_at.desc
        var filters = new Dictionary<string, string>
        {
            ["user_id"] = $"eq.{userId}"
        };
        return await _supabaseService.GetAsync<Board>("boards", filters, orderBy: "updated_at.desc");
    }

    /// <summary>
    /// Creates a new board for the current user.
    /// </summary>
    /// <param name="name">The name of the board (will be trimmed).</param>
    /// <returns>The created board with server-generated values.</returns>
    /// <exception cref="UnauthorizedAccessException">Thrown when user is not authenticated.</exception>
    /// <exception cref="ArgumentException">Thrown when name is null or whitespace.</exception>
    public async Task<Board> CreateBoardAsync(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Board name cannot be empty.", nameof(name));
        }

        var userId = await GetCurrentUserIdAsync();
        if (userId == Guid.Empty)
        {
            throw new UnauthorizedAccessException("User is not authenticated.");
        }

        var newBoard = new Board
        {
            UserId = userId,
            Name = name.Trim()
            // Id, CreatedAt, and UpdatedAt are generated by Supabase
        };

        // Call Supabase API: POST /rest/v1/boards
        return await _supabaseService.PostAsync("boards", newBoard);
    }

    // TODO: Implement remaining CRUD methods (Stories B3.3-B3.4)
    // - GetBoardByIdAsync
    // - UpdateBoardAsync
    // - DeleteBoardAsync

    /// <summary>
    /// Gets the current authenticated user's ID from claims.
    /// </summary>
    private async Task<Guid> GetCurrentUserIdAsync()
    {
        var authState = await _authStateProvider.GetAuthenticationStateAsync();
        var user = authState.User;

        if (user?.Identity?.IsAuthenticated == true)
        {
            var userIdClaim = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (!string.IsNullOrEmpty(userIdClaim) && Guid.TryParse(userIdClaim, out var userId))
            {
                return userId;
            }
        }

        return Guid.Empty;
    }
}
